### ISSUE TITLE
APK build not installable candidate

### ISSUE THREAD

**Issue by martinberlin** [bitbank2/ESLImageTransfer#1]
![Screenshot_20220116_120344877_Package installer](https://user-images.githubusercontent.com/2692928/149657311-d303f8db-e5d5-4f2b-a936-32ceadb2ffd9.jpg)

I will research later to see if I can discover why it's that. My build is slightly bigger (3.2 MB)
I guess until this works it would be the best not to offer the built APK to download. And maybe offer alternativally one that works even if it's not the last version. I can build it for you till we find out why it's coming out like this.

**Comment by atc1441** [comment]
The debug.apk is only working on the device it was build on.

A signed apk needs to be generated to be shareable

**Comment by bitbank2** [comment]
This is the problem with open source Android projects. I will need to create a signing key, but not share it.

**Comment by martinberlin** [comment]
Hello @atc1441

> The debug.apk is only working on the device it was build on.

I disagree with this. My Android Studio does not know at all what mobile I have and I can build an APK that it is an install candidate in any device. Here is the proof:
https://sync.luckycloud.de/d/0c0d14f4949f4290b0b9

I installed that APK in 2 different devices and didn't have any problem with it, only need to accept the security risks. 

> A signed apk needs to be generated to be shareable

This is also not correct IMHO. A signed APK is only needed if you want to upload the App to Google Play. But you can upload a debug APK also anywhere and share it, only the owner of the Android has to accept to install it and take the risk. 
The best would be to upload the installable generated by Larry in Google developers zone as a debug APK and find out why it's not installable.

@bitbank2 I'm quite sure that is not a problem of signature. It has to be something different, I bet you upload a signed APK and I would also not able to install it.

I tried so far installing the generated APK on this targets
My Hisense Android v. 10 correct
A pixel 3 with version 12 also correct
![Screenshot_20220116-144936](https://user-images.githubusercontent.com/2692928/149663014-45ee72b7-b046-4612-abcb-ba529288abe6.png)

A very old Android - could not parse package

**Comment by atc1441** [comment]
There are still different debug versions,
The one created when your phone is connected to Android studio is fixed to that device as far i know, when one is build in general it is different.

But not sure about the backrounds here

**Comment by martinberlin** [comment]
That can be. I built that APK without any debug phone connected, just cloned the repo and hit build. The resulting binary should be installable in any android device, provided has the min. required version of Android.
